# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkIiGtYFxo2dPJAGkCUfDUQDMLtekS5h
"""

import pandas as pd

titan = pd.read_csv('/content/drive/MyDrive/Dataset/Titanic Dataset/train.csv')
gender = pd.read_csv('/content/drive/MyDrive/Dataset/Titanic Dataset/gender_submission.csv')

titan.info()

gender.info()

titan.head()

gender.head()

"""## EDA"""

titan.isnull().sum()

gender.isnull().sum()

titan.duplicated().sum()

gender.duplicated().sum()

"""## **How does passenger class influence survival outcomes on the Titanic?**"""

print(titan['Pclass'].unique())

import matplotlib.pyplot as plt

survive_count = (titan.groupby("Pclass")["Survived"]
                 .sum().reset_index())

total_per_class = titan.groupby("Pclass").size().reset_index(name="Total") # Grouping based on Passenger Class
survive_rate = survive_count.merge(total_per_class, on="Pclass")
survive_rate["SurvivalPercent"] = (survive_rate["Survived"] / survive_rate["Total"]) * 100 # Count survive rate

# plot
plt.figure(figsize=(8,6))
bars = plt.bar(survive_count["Pclass"], survive_count["Survived"])
plt.xlabel("Passenger Class (Pclass)")
plt.ylabel("Number of Survivors")
plt.title("Number of Survivors by Passenger Class")
max_height = survive_count["Survived"].max()
plt.ylim(0, max_height * 1.15)

# Annotate percentage
for bar, pct in zip(bars, survive_rate["SurvivalPercent"]):
  height = bar.get_height()
  plt.text(
      bar.get_x() + bar.get_width() / 2,
      height + 2,
      f"{pct:.1f}%",
      ha="center",
      va="bottom"
  )

plt.show()

"""The analysis reveals that survival on the Titanic was not random, but strongly shaped by social structure. While the absolute number of survivors is highest among Upper Class passengers, survival probability varies significantly across both passenger class and gender."""

print(titan["Sex"].unique())

gender_count = (
      titan.groupby(["Pclass", "Sex"])["Survived"]
      .sum()
      .reset_index()
) # Total number of survivors for each Pclass and Sex

total_gender = (
    titan.groupby(["Pclass", "Sex"])
    .size()
    .reset_index(name="Total")
) # Total number of passengers for each Pclass and Sex

gender_rate = gender_count.merge(total_gender, on=["Pclass", "Sex"])
gender_rate["SurvivalPercent"] = (
    gender_rate["Survived"] / gender_rate["Total"] * 100
) # Survive rate per Pclass

plt.figure(figsize=(8,6))
width = 0.35
pclass = sorted(gender_rate["Pclass"].unique())
x = range(len(pclass))
sex_list = ["male", "female"]

for i, sex in enumerate(sex_list): # Prepare bar for each pclass and sex
    subset = gender_rate[gender_rate["Sex"] == sex]
    plt.bar(
        [pos + i * width for pos in x],
        subset["SurvivalPercent"],
        width=width,
        label=sex
    )

plt.xticks(
    [pos + width / 2 for pos in x],
    ["Upper", "Middle", "Lower"]
)

plt.xlabel("Passenger Class (Pclass)")
plt.ylabel("Survival Rate (%)")
plt.title("Survival Rate by Passenger Class and Sex")
plt.ylim(0, 100)
plt.legend(title="Sex")
plt.show()

"""Females consistently exhibit substantially higher survival rates than males across all classes, with the advantage being most pronounced in higher classes. This pattern indicates that survival outcomes were driven by a combination of gender-based evacuation priorities and class-based access to safety, rather than chance alone.

## **Do passengers traveling alone differ in survival outcomes compared to those  traveling with family?**
"""

# Create new row stand for passenger traveling alone
titan["IsAlone"] = ((titan["SibSp"] + titan["Parch"]) == 0).astype(int) # If Si

# Percentage Survival Rate of Passenger that's traveling alone
alone_rate = (
    titan.groupby("IsAlone")["Survived"].mean().reset_index()
)
alone_rate["SurvivalPercent"] = alone_rate["Survived"] * 100

#
alone_rate["Group"] = alone_rate["IsAlone"].map({
    1: "Alone",
    0: "With Family"
})

plt.figure(figsize=(7,5))
bars = plt.bar(
    alone_rate["Group"],
    alone_rate["SurvivalPercent"]
)

plt.xlabel("Passenger Group")
plt.ylabel("Survival Rate (%)")
plt.title("Survival Rate: Traveling Alone vs With Family")
plt.ylim(0, 100)

for bar in bars:
  height = bar.get_height()
  plt.text(
      bar.get_x() + bar.get_width() / 2,
      height + 2,
      f"{height:.1f}%",
      ha="center",
      va="bottom"
  )
plt.show()

