# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkIiGtYFxo2dPJAGkCUfDUQDMLtekS5h
"""

import pandas as pd

titan = pd.read_csv('/content/drive/MyDrive/Dataset/Titanic Dataset/train.csv')
gender = pd.read_csv('/content/drive/MyDrive/Dataset/Titanic Dataset/gender_submission.csv')

titan.info()

gender.info()

titan.head()

gender.head()

"""## EDA"""

titan.isnull().sum()

gender.isnull().sum()

titan.duplicated().sum()

gender.duplicated().sum()

"""## **How does passenger class influence survival outcomes on the Titanic?**"""

print(titan['Pclass'].unique())

import matplotlib.pyplot as plt

survive_count = (titan.groupby("Pclass")["Survived"]
                 .sum().reset_index())

total_per_class = titan.groupby("Pclass").size().reset_index(name="Total") # Grouping based on Passenger Class
survive_rate = survive_count.merge(total_per_class, on="Pclass")
survive_rate["SurvivalPercent"] = (survive_rate["Survived"] / survive_rate["Total"]) * 100 # Count survive rate

# plot
plt.figure(figsize=(8,6))
bars = plt.bar(survive_count["Pclass"], survive_count["Survived"])
plt.xlabel("Passenger Class (Pclass)")
plt.ylabel("Number of Survivors")
plt.title("Number of Survivors by Passenger Class")
max_height = survive_count["Survived"].max()
plt.ylim(0, max_height * 1.15)

# Annotate percentage
for bar, pct in zip(bars, survive_rate["SurvivalPercent"]):
  height = bar.get_height()
  plt.text(
      bar.get_x() + bar.get_width() / 2,
      height + 2,
      f"{pct:.1f}%",
      ha="center",
      va="bottom"
  )

plt.show()

gender_count = (
      titan.groupby(["Pclass", "Sex"])["Survived"]
      .sum()
      .reset_index()
) # grouping Survivor based on "sex" and "Pclass"

total_gender = (
    titan.groupby(["Pclass", "Sex"])
    .size()
    .reset_index(name="Total")
) # Summarize total

gender_rate = gender_count.merge(total_gender, on=["Pclass", "Sex"])
gender_rate["SurvivalPercent"] = (
    gender_rate["Survived"] / gender_rate["Total"] * 100

)

