# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkIiGtYFxo2dPJAGkCUfDUQDMLtekS5h
"""

import pandas as pd

titan = pd.read_csv('/content/drive/MyDrive/Dataset/Titanic Dataset/train.csv')
gender = pd.read_csv('/content/drive/MyDrive/Dataset/Titanic Dataset/gender_submission.csv')

titan.info()

gender.info()

titan.head()

gender.head()

"""## EDA"""

titan.isnull().sum()

gender.isnull().sum()

titan.duplicated().sum()

gender.duplicated().sum()

"""## **How does passenger class influence survival outcomes on the Titanic?**"""

print(titan['Pclass'].unique())

import matplotlib.pyplot as plt

survive_count = (titan.groupby("Pclass")["Survived"]
                 .sum().reset_index())

total_per_class = titan.groupby("Pclass").size().reset_index(name="Total") # Grouping based on Passenger Class
survive_rate = survive_count.merge(total_per_class, on="Pclass")
survive_rate["SurvivalPercent"] = (survive_rate["Survived"] / survive_rate["Total"]) * 100 # Count survive rate

# plot
plt.figure(figsize=(8,6))
bars = plt.bar(survive_count["Pclass"], survive_count["Survived"])
plt.xlabel("Passenger Class (Pclass)")
plt.ylabel("Number of Survivors")
plt.title("Number of Survivors by Passenger Class")
max_height = survive_count["Survived"].max()
plt.ylim(0, max_height * 1.15)

# Annotate percentage
for bar, pct in zip(bars, survive_rate["SurvivalPercent"]):
  height = bar.get_height()
  plt.text(
      bar.get_x() + bar.get_width() / 2,
      height + 2,
      f"{pct:.1f}%",
      ha="center",
      va="bottom"
  )

plt.show()

survive_count

"""The analysis reveals that survival on the Titanic was not random, but strongly shaped by social structure. While the absolute number of survivors is highest among Upper Class passengers, survival probability varies significantly across both passenger class and gender."""

print(titan["Sex"].unique())

titan.info()

gender_count = (
      titan.groupby(["Pclass", "Sex"])["Survived"]
      .sum()
      .reset_index()
) # Total number of survivors for each Pclass and Sex

total_gender = (
    titan.groupby(["Pclass", "Sex"])
    .size()
    .reset_index(name="Total")
) # Total number of passengers for each Pclass and Sex

gender_rate = gender_count.merge(total_gender, on=["Pclass", "Sex"])
gender_rate["SurvivalPercent"] = (
    gender_rate["Survived"] / gender_rate["Total"] * 100
) # Survive rate per Pclass

plt.figure(figsize=(8,6))
width = 0.35
pclass = sorted(gender_rate["Pclass"].unique())
x = range(len(pclass))
sex_list = ["male", "female"]

bars_dict = {}
for i, sex in enumerate(sex_list): # Prepare bar for each pclass and sex
  subset = gender_rate[gender_rate["Sex"] == sex]
  bars = plt.bar(
      [pos + i * width for pos in x],
      subset["Survived"], # subset["SurvivalPercent"] -> subset["Survived"]
      width=width,
      label=sex
  )
  bars_dict[sex] = (bars, subset)

plt.xticks(
    [pos + width / 2 for pos in x],
    ["Upper", "Middle", "Lower"]
)

plt.xlabel("Passenger Class (Pclass)")
plt.ylabel("Survival Rate (%)")
plt.title("Survival Rate by Passenger Class and Sex")
max_height = gender_count["Survived"].max()
plt.ylim(0, max_height * 1.15)

# Annotate Survive Percentage
for sex, (bars, subset) in bars_dict.items():
  for bar, pct in zip(bars, subset["SurvivalPercent"]):
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height + 2,
        f"{pct:.1f}%",
        ha="center",
        va="bottom"
    )

plt.legend(title="Sex")
plt.show()

total_gender

"""Females consistently exhibit substantially higher survival rates than males across all classes, with the advantage being most pronounced in higher classes. This pattern indicates that survival outcomes were driven by a combination of gender-based evacuation priorities and class-based access to safety, rather than chance alone.

## **Do passengers traveling alone differ in survival outcomes compared to those  traveling with family?**
"""

# Create new row stand for passenger traveling alone
titan["IsAlone"] = ((titan["SibSp"] + titan["Parch"]) == 0).astype(int) # If Si

alone_pass = (
    titan[titan["Survived"] == 1].groupby("IsAlone").size().reset_index(name="AloneSurv")
) # Count Survivor from "IsAlone" group

# Total Passenger per group (for calculate survival rate)
total_pass = (titan.groupby("IsAlone").size().reset_index(name="Total"))

alone_rate = alone_pass.merge(total_pass, on="IsAlone") # Merge survivor count and total passengers

# Percentage Survival Rate of Passenger that's traveling alone
alone_rate["SurvivalPercent"] = (alone_rate["AloneSurv"] / alone_rate["Total"] * 100)

# Mapping the "IsAlone"category
alone_rate["Group"] = alone_rate["IsAlone"].map({
    1: "Alone",
    0: "With Family"
})

alone_rate

plt.figure(figsize=(7,5))
bars = plt.bar(
    alone_rate["Group"],
    alone_rate["AloneSurv"]
)

plt.xlabel("Passenger Group")
plt.ylabel("Number of Survivor")
plt.title("Survival Rate: Traveling Alone vs With Family")
plt.ylim(0, alone_rate["AloneSurv"].max() * 1.15)

for bar, pct in zip(bars, alone_rate["SurvivalPercent"]):
  height = bar.get_height()
  plt.text(
      bar.get_x() + bar.get_width() / 2,
      height + 2,
      f"{pct:.1f}%",
      ha="center",
      va="bottom"
  )
plt.show()

"""Passengers traveling with family demonstrate more favorable survival outcomes compared to those traveling alone. Beyond the higher number of survivors, the substantially higher survival rate among passengers with family suggests that travel context may be associated with differences in access, support, or prioritization during evacuation. In contrast, passengers traveling alone show both a lower survivor count and a lower survival proportion, indicating a comparatively more vulnerable position. While this analysis does not establish causality, it highlights family presence as a meaningful factor associated with survival patterns on the Titanic.

## **Does passenger class shape the age profile of survivors, or do survivors accross classes share similar age characteristics?**
"""

import matplotlib.pyplot as plt

# Filter survivors with known age
age_survivors = titan[
  (titan["Survived"] == 1) &
  (titan["Age"].notna())
]

# Prepare age data per passenger class
age_data = [
  age_survivors[age_survivors["Pclass"] == 1]["Age"],
  age_survivors[age_survivors["Pclass"] == 2]["Age"],
  age_survivors[age_survivors["Pclass"] == 3]["Age"]
]

# Plot
plt.figure(figsize=(10, 8))
bp = plt.boxplot(age_data, labels=["Upper", "Middle", "Lower"])

# Annotate median age
medians = [data.median() for data in age_data]
for i, median in enumerate(medians, start=1):
  plt.text(
      i,
      median + 1.5,
      f"Median: {median:.0f}",
      ha="center",
      fontsize=9,
      color="black"
  )

plt.xlabel("Passenger Class (Pclass)")
plt.ylabel("Age")
plt.title("Age Distribution of Survivors by Passenger Class")

plt.show()

"""Passengers who survived in higher classes were generally older, while survivors in lower classes were mostly younger. The middle class sits between the two, showing a gradual change in survivor age from upper to lower class. This suggests that survival on the Titanic was associated not only with passenger class, but also with differences in the age profile within each class.

**Note:**

**While survivors in higher passenger classes appear to be older on average compared to those in lower classes, this observation is based only on passengers with known age values. Since a large number of age records are missing, the observed pattern may not fully represent all survivors. Additional analysis would be needed to better understand how missing age data might affect this distribution.**
"""

